from typing import Any, Optional

from requests_async.models import Response

async def request(method: str, url: str, **kwargs: object) -> Response: ...
async def get(url: str, params: Optional[Any] = ..., **kwargs: object) -> Response: ...
async def options(url: str, **kwargs: object) -> Response: ...
async def head(url: str, **kwargs: object) -> Response: ...
async def post(
    url: str, data: Optional[Any] = ..., json: Optional[Any] = ..., **kwargs: object
) -> Response: ...
async def put(url: str, data: Optional[Any] = ..., **kwargs: object) -> Response: ...
async def patch(url: str, data: Optional[Any] = ..., **kwargs: object) -> Response: ...
async def delete(url: str, **kwargs: object) -> Response: ...
