# Generated by Django 3.0.3 on 2020-02-16 17:11

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_account_payload'),
    ]

    operations = [
        migrations.CreateModel(
            name='PullRequestActivity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField()),
                ('total_opened', models.IntegerField()),
                ('total_merged', models.IntegerField()),
                ('total_closed', models.IntegerField()),
                ('kodiak_approved', models.IntegerField()),
                ('kodiak_merged', models.IntegerField()),
                ('kodiak_updated', models.IntegerField()),
                ('account', models.ForeignKey(db_column='github_installation_id', db_constraint=False, on_delete=django.db.models.deletion.CASCADE, to='core.Account', to_field='github_installation_id')),
            ],
            options={
                'db_table': 'pull_request_activity',
            },
        ),
        migrations.AddConstraint(
            model_name='pullrequestactivity',
            constraint=models.UniqueConstraint(fields=('date', 'account'), name='unique_pull_request_activity'),
        ),
    ]
