# Generated by Django 3.0.3 on 2020-02-17 01:57

from django.contrib.postgres.operations import CreateExtension
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_auto_20200216_1711"),
    ]

    operations = [CreateExtension("uuid-ossp")]
