# Generated by Django 3.0.3 on 2020-02-17 04:54

from django.db import migrations


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ("core", "0007_auto_20200217_0345"),
    ]

    operations = [
        migrations.RunSQL(
            "CREATE INDEX CONCURRENTLY payload_installation_id_idx on github_event (((payload -> 'installation' ->> 'id')::integer))",
            reverse_sql="DROP INDEX IF EXISTS payload_installation_id_idx",
        ),
    ]
