# Generated by Django 3.0.3 on 2020-02-17 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_uuid_extension"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pullrequestactivity",
            name="date",
            field=models.DateField(db_index=True),
        ),
    ]
