# Generated by Django 3.0.3 on 2020-03-08 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0010_auto_20200220_0116"),
    ]

    operations = [
        migrations.AddField(
            model_name="accountmembership",
            name="role",
            field=models.CharField(
                choices=[("admin", "Admin"), ("member", "Member")],
                default="member",
                help_text="User's GitHub-defined role for the associated account.",
                max_length=255,
            ),
            preserve_default=False,
        ),
    ]
