# Generated by Django 3.0.3 on 2020-03-15 15:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0013_auto_20200310_0412"),
    ]

    operations = [
        migrations.AddField(
            model_name="account",
            name="trial_expiration",
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name="account",
            name="trial_start",
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name="account",
            name="trial_started_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="core.User",
            ),
        ),
    ]
