# Generated by Django 3.0.3 on 2020-03-15 17:13

import django.contrib.postgres.fields.citext
from django.contrib.postgres.operations import CITextExtension
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0014_auto_20200315_1510"),
    ]

    operations = [
        CITextExtension(),
        migrations.AddField(
            model_name="account",
            name="billing_email",
            field=django.contrib.postgres.fields.citext.CIEmailField(
                max_length=254, null=True
            ),
        ),
    ]
