# Generated by Django 3.0.3 on 2020-06-09 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0019_account_stripe_plan_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="stripecustomerinformation",
            name="customer_currency",
            field=models.CharField(
                default="usd",
                help_text="Three-letter ISO code for the currency the customer can be charged in for recurring billing purposes.",
                max_length=255,
            ),
            preserve_default=False,
        ),
    ]
