# Generated by Django 3.0.3 on 2020-06-10 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0020_stripecustomerinformation_customer_currency"),
    ]

    operations = [
        migrations.AlterField(
            model_name="stripecustomerinformation",
            name="customer_currency",
            field=models.CharField(
                help_text="Three-letter ISO code for the currency the customer can be charged in for recurring billing purposes.",
                max_length=255,
                null=True,
            ),
        ),
    ]
