# Generated by Django 3.0.3 on 2020-06-26 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0023_account_limit_billing_access_to_owners"),
    ]

    operations = [
        migrations.AddField(
            model_name="user", name="text", field=models.TextField(default=""),
        ),
    ]
