from typing import Any

from typing_extensions import Self

class BoundLoggerBase:
    def __init__(self, logger: Any, processors: Any, context: Any) -> None: ...
    def bind(self, **new_values: Any) -> Self: ...
    def unbind(self, *keys: str) -> Self: ...
    def try_unbind(self, *keys: str) -> Self: ...
    def new(self, **new_values: Any) -> Self: ...
