from typing import Any

class RegexError(Exception):
    message: str
    def __init__(self, message: str, *args: Any) -> None: ...

class RegexSyntaxError(RegexError): ...
class CompiledTooBigError(RegexError): ...
