"""initial migration

Revision ID: fb3761f0a9e7
Revises: 
Create Date: 2020-02-02 09:21:15.719627

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'fb3761f0a9e7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # pycrypto is not enabled by default and we need it for gen_random_uuid().
    op.execute('CREATE EXTENSION IF NOT EXISTS "pgcrypto"')
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', postgresql.UUID(as_uuid=True), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('github_id', sa.Integer(), nullable=False),
    sa.Column('github_login', sa.String(), nullable=False),
    sa.Column('github_access_token', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_github_id'), 'user', ['github_id'], unique=True)
    op.create_index(op.f('ix_user_github_login'), 'user', ['github_login'], unique=True)
    op.create_index(op.f('ix_user_id'), 'user', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_id'), table_name='user')
    op.drop_index(op.f('ix_user_github_login'), table_name='user')
    op.drop_index(op.f('ix_user_github_id'), table_name='user')
    op.drop_table('user')
    # ### end Alembic commands ###
