#!/usr/bin/env sh
set -ex
docker login -u "$DOCKER_USER" -p "$DOCKER_PASS"

# https://circleci.com/docs/2.0/env-vars/#circleci-built-in-environment-variables
LABEL="$CIRCLE_SHA1"
if [[ ! -z $CIRCLE_TAG ]]; then
    LABEL="$CIRCLE_TAG"
fi

docker build --tag chdsbd/kodiak:$LABEL .
docker push chdsbd/kodiak:$LABEL
