#!/usr/bin/env sh
set -eu
DOCKER_HUB_REPO='cdignam/kodiak'
docker login --username="$DOCKER_USER" --password="$DOCKER_PASS"
docker login --username=_ --password=$HEROKU_API_TOKEN registry.heroku.com

set -x

# https://circleci.com/docs/2.0/env-vars/#circleci-built-in-environment-variables
LABEL="$CIRCLE_SHA1"
if [[ ! -z $CIRCLE_TAG ]]; then
    LABEL="$CIRCLE_TAG"
fi

DOCKER_HUB_TAG=$DOCKER_HUB_REPO:$LABEL
HEROKU_TAG_PROD=registry.heroku.com/kodiak-prod/web
HEROKU_TAG_STAGE=registry.heroku.com/kodiak-stage/web
docker build --tag $DOCKER_HUB_TAG --tag $HEROKU_TAG_PROD --tag $HEROKU_TAG_STAGE .
docker push $DOCKER_HUB_TAG
docker push $HEROKU_TAG_STAGE
docker push $HEROKU_TAG_PROD
