#!/usr/bin/env sh
set -e
DOCKER_HUB_REPO='cdignam/kodiak'
docker login --username="$DOCKER_USER" --password="$DOCKER_PASS"
docker login --username=_ --password=$HEROKU_API_TOKEN registry.heroku.com

set -x

# https://circleci.com/docs/2.0/env-vars/#circleci-built-in-environment-variables
LABEL="$CIRCLE_SHA1"
if [[ ! -z $CIRCLE_TAG ]]; then
    LABEL="$CIRCLE_TAG"
fi

docker build --tag $DOCKER_HUB_REPO:$LABEL .
docker push $DOCKER_HUB_REPO:$LABEL
