#!/usr/bin/env python3
import subprocess
import sys


def main(path: str) -> None:
    """

    - if the branch doesn't have a pull request
    """

    res = subprocess.run(["git", "diff", "--name-only", "--exit-code", "master...", path], capture_output=True)
    # if we have changes, return now
    if res.returncode == 0:
        subprocess.run(["circleci", "step", "halt"], check=True)
        return
    if res.returncode == 1:
        return
    raise ValueError(f"Unexpected return code {res.returncode}")


if __name__ == '__main__':
    progname = sys.argv[0]
    path = sys.argv[1]
    main(path)
