#!/usr/bin/env bash
set -ex

cd $(dirname $(dirname "$0"))

# format code
if [[ $CI ]]; then
    poetry run black --check .
    poetry run isort --check-only
else
    poetry run black .
    poetry run isort -y
fi

# type check code
poetry run mypy . web-api web-api/alembic

# lint
poetry run flake8 kodiak web-api/app web-api/alembic
poetry run pylint --rcfile='.pylintrc' kodiak web-api/app web-api/alembic/env.py
