#!/usr/bin/env bash
set -ex

cd $(dirname $(dirname "$0"))

# format code
if [[ $CI ]]; then
    poetry run black --check .
    poetry run isort --check-only
else
    poetry run black .
    poetry run isort -y
fi

# type check code
poetry run mypy . web_api web_api/web_api/migrations web_api/web_api/migrations/versions

# lint
poetry run flake8 kodiak web_api
poetry run pylint --rcfile='.pylintrc' kodiak web_api/web_api web_api/web_api/migrations/*.py web_api/web_api/migrations/versions/*.py
