#!/usr/bin/env bash

set -o pipefail
set -o errexit
set -o nounset


for f in $(git ls-files); do
  if [ -f "$f" ]; then
    # matches shebang as well as shell file endings
    if grep -Eq '^#!(.*/|.*env +)(sh|bash|ksh)' "$f" || [[ "$f" =~ \.(sh|bash|ksh)$ ]]; then
      echo "$f"
      shellcheck "$f"
    fi
  fi
done
