#!/bin/sh
# configure react-scripts to open correct domain on start. Also configure API routing for JS bundle.
# https://github.com/facebook/create-react-app/blob/8b0dd54c7a7488d46a43ff6d1c67a6b41c31feb1/packages/react-scripts/scripts/start.js#L61
HOST=app.localhost.kodiakhq.com exec node scripts/start.js
