# Generated by Django 3.0.3 on 2020-02-09 17:44

import uuid

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web_api", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="GitHubEvent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                ("event_name", models.CharField(db_index=True, max_length=255)),
                (
                    "payload",
                    django.contrib.postgres.fields.jsonb.JSONField(default=dict),
                ),
            ],
            options={"db_table": "github_event",},
        ),
    ]
