# Generated by Django 3.0.3 on 2020-02-15 20:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("web_api", "0003_auto_20200215_1733"),
    ]

    operations = [
        migrations.RenameField(
            model_name="account",
            old_name="github_id",
            new_name="github_installation_id",
        ),
    ]
