# Generated by Django 3.0.3 on 2020-02-15 21:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("web_api", "0004_auto_20200215_2015"),
    ]

    operations = [
        migrations.AlterField(
            model_name="account",
            name="github_account_id",
            field=models.IntegerField(
                help_text="GitHub ID for account with installation.", unique=True
            ),
        ),
        migrations.AlterField(
            model_name="account",
            name="github_account_login",
            field=models.CharField(
                help_text="GitHub username for account with installation.",
                max_length=255,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="account",
            name="github_installation_id",
            field=models.IntegerField(
                help_text="GitHub App Installation ID.", unique=True
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="github_access_token",
            field=models.CharField(
                help_text="OAuth token for the GitHub user.", max_length=255
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="github_id",
            field=models.IntegerField(
                help_text="GitHub ID of the GitHub user account.", unique=True
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="github_login",
            field=models.CharField(
                help_text="GitHub username of the GitHub account.",
                max_length=255,
                unique=True,
            ),
        ),
    ]
