# Generated by Django 3.0.3 on 2020-02-16 03:02

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("web_api", "0005_auto_20200215_2156"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="account",
            name="payload",
        ),
    ]
