# Generated by Django 3.0.3 on 2020-02-20 01:16

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("web_api", "0009_pullrequestactivityprogress"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserPullRequestActivity",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                ("github_installation_id", models.IntegerField(db_index=True)),
                (
                    "github_repository_name",
                    models.CharField(db_index=True, max_length=255),
                ),
                ("github_pull_request_number", models.IntegerField(db_index=True)),
                ("github_user_login", models.CharField(db_index=True, max_length=255)),
                ("github_user_id", models.IntegerField(db_index=True)),
                ("is_private_repository", models.BooleanField(db_index=True)),
                ("activity_date", models.DateField(db_index=True)),
            ],
            options={
                "db_table": "user_pull_request_activity",
            },
        ),
        migrations.CreateModel(
            name="UserPullRequestActivityProgress",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                (
                    "min_date",
                    models.DateTimeField(
                        db_index=True,
                        help_text="Date we should use as our minimum date for future aggregation jobs. Anything before this date is 'locked'.",
                    ),
                ),
            ],
            options={
                "db_table": "user_pull_request_activity_progress",
            },
        ),
        migrations.AddConstraint(
            model_name="userpullrequestactivity",
            constraint=models.UniqueConstraint(
                fields=(
                    "github_installation_id",
                    "github_repository_name",
                    "github_pull_request_number",
                    "github_user_id",
                    "activity_date",
                ),
                name="unique_user_pull_request_activity",
            ),
        ),
    ]
