# Generated by Django 3.0.3 on 2020-03-08 22:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("web_api", "0011_accountmembership_role"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="accountmembership",
            constraint=models.CheckConstraint(
                check=models.Q(role__in=["admin", "member"]), name="role_valid"
            ),
        ),
    ]
