# Generated by Django 3.0.3 on 2020-04-05 15:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("web_api", "0015_remove_stripecustomerinformation_customer_delinquent"),
    ]

    operations = [
        migrations.AlterField(
            model_name="stripecustomerinformation",
            name="payment_method_card_exp_month",
            field=models.CharField(
                help_text="Two-digit number representing the card`s expiration month.",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="stripecustomerinformation",
            name="payment_method_card_exp_year",
            field=models.CharField(
                help_text="Four-digit number representing the card`s expiration year.",
                max_length=255,
                null=True,
            ),
        ),
    ]
