# Generated by Django 3.0.3 on 2020-04-05 19:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("web_api", "0016_auto_20200405_1511"),
    ]

    operations = [
        migrations.AddField(
            model_name="account",
            name="trial_email",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
