# Generated by Django 3.0.3 on 2020-05-02 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web_api", "0017_account_trial_email"),
    ]

    operations = [
        migrations.AlterField(
            model_name="stripecustomerinformation",
            name="payment_method_id",
            field=models.CharField(
                db_index=True,
                help_text="Unique identifier for Stripe PaymentMethod object.",
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="stripecustomerinformation",
            name="plan_id",
            field=models.CharField(
                db_index=True,
                help_text="Unique identifier for Stripe Plan object.",
                max_length=255,
            ),
        ),
    ]
