# Generated by Django 3.0.3 on 2020-06-10 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web_api", "0018_auto_20200502_1849"),
    ]

    operations = [
        migrations.AddField(
            model_name="account",
            name="stripe_plan_id",
            field=models.CharField(
                help_text="Stripe plan_id to use when creating subscription. Overrides settings.STRIPE_PLAN_ID if provided. We only need to set this when we provide a custom plan for a given user.",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="stripecustomerinformation",
            name="customer_currency",
            field=models.CharField(
                help_text="Three-letter ISO code for the currency the customer can be charged in for recurring billing purposes.",
                max_length=255,
                null=True,
            ),
        ),
    ]
