# Generated by Django 3.0.3 on 2020-06-13 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web_api", "0019_auto_20200610_0006"),
    ]

    operations = [
        migrations.AddField(
            model_name="stripecustomerinformation",
            name="customer_address_city",
            field=models.CharField(
                help_text="City, district, suburb, town, or village.",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="stripecustomerinformation",
            name="customer_address_country",
            field=models.CharField(
                help_text="Two-letter country code (ISO 3166-1 alpha-2).",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="stripecustomerinformation",
            name="customer_address_line1",
            field=models.CharField(
                help_text="Address line 1 (e.g., street, PO Box, or company name).",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="stripecustomerinformation",
            name="customer_address_line2",
            field=models.CharField(
                help_text="Address line 2 (e.g., apartment, suite, unit, or building).",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="stripecustomerinformation",
            name="customer_address_postal_code",
            field=models.CharField(
                help_text="ZIP or postal code.", max_length=255, null=True
            ),
        ),
        migrations.AddField(
            model_name="stripecustomerinformation",
            name="customer_address_state",
            field=models.CharField(
                help_text="State, county, province, or region.",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="stripecustomerinformation",
            name="customer_name",
            field=models.CharField(
                help_text="The customer’s full name or business name.",
                max_length=255,
                null=True,
            ),
        ),
    ]
