# Generated by Django 3.0.3 on 2020-06-21 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web_api", "0022_remove_account_stripe_plan_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="account",
            name="limit_billing_access_to_owners",
            field=models.BooleanField(default=False),
        ),
    ]
