# Generated by Django 3.0.3 on 2020-10-13 03:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("web_api", "0025_auto_20200902_0052"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="stripecustomerinformation", name="customer_currency",
        ),
    ]
