# Generated by Django 3.0.3 on 2020-10-24 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web_api", "0025_auto_20200902_0052"),
    ]

    operations = [
        migrations.AlterField(
            model_name="stripecustomerinformation",
            name="customer_currency",
            field=models.CharField(
                db_column="customer_currency",
                help_text="Three-letter ISO code for the currency the customer can be charged in for recurring billing purposes.",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="stripecustomerinformation",
            name="payment_method_card_brand",
            field=models.CharField(
                db_column="payment_method_card_brand",
                help_text="Card brand. Can be `amex`, `diners`, `discover`, `jcb`, `mastercard`, `unionpay`, `visa`, or `unknown`.",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="stripecustomerinformation",
            name="payment_method_card_exp_month",
            field=models.CharField(
                db_column="payment_method_card_exp_month",
                help_text="Two-digit number representing the card’s expiration month.",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="stripecustomerinformation",
            name="payment_method_card_exp_year",
            field=models.CharField(
                db_column="payment_method_card_exp_year",
                help_text="Four-digit number representing the card’s expiration year.",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="stripecustomerinformation",
            name="payment_method_card_last4",
            field=models.CharField(
                db_column="payment_method_card_last4",
                help_text="The last four digits of the card.",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="stripecustomerinformation",
            name="payment_method_id",
            field=models.CharField(
                db_column="payment_method_id",
                db_index=True,
                help_text="Unique identifier for Stripe PaymentMethod object.",
                max_length=255,
            ),
        ),
    ]
