# Generated by Django 3.0.3 on 2020-10-14 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web_api", "0026_remove_stripecustomerinformation_customer_currency"),
    ]

    operations = [
        migrations.AddField(
            model_name="stripecustomerinformation",
            name="plan_product_name",
            field=models.CharField(
                help_text="The product's name. Displayed to users.",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="stripecustomerinformation",
            name="upcoming_invoice_total",
            field=models.IntegerField(
                help_text="total cost in cents to be billed to customer via next subscription invoice.",
                null=True,
            ),
        ),
    ]
