# Generated by Django 3.0.3 on 2020-10-14 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web_api", "0027_auto_20201014_0130"),
    ]

    operations = [
        migrations.AddField(
            model_name="stripecustomerinformation",
            name="subscription_cancel_at",
            field=models.IntegerField(
                help_text="A date in the future at which the subscription will automatically get canceled.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="stripecustomerinformation",
            name="subscription_cancel_at_period_end",
            field=models.BooleanField(
                help_text="If the subscription has been canceled with the at_period_end flag set to true, cancel_at_period_end on the subscription will be true.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="stripecustomerinformation",
            name="subscription_canceled_at",
            field=models.IntegerField(
                help_text="If the subscription has been canceled, the date of that cancellation. If the subscription was canceled with cancel_at_period_end, canceled_at will still reflect the date of the initial cancellation request, not the end of the subscription period when the subscription is automatically moved to a canceled state.",
                null=True,
            ),
        ),
    ]
