# Generated by Django 3.0.3 on 2020-10-18 02:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("web_api", "0028_auto_20201014_0259"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="stripecustomerinformation", name="payment_method_card_brand",
        ),
        migrations.RemoveField(
            model_name="stripecustomerinformation",
            name="payment_method_card_exp_month",
        ),
        migrations.RemoveField(
            model_name="stripecustomerinformation", name="payment_method_card_exp_year",
        ),
        migrations.RemoveField(
            model_name="stripecustomerinformation", name="payment_method_card_last4",
        ),
        migrations.RemoveField(
            model_name="stripecustomerinformation", name="payment_method_id",
        ),
    ]
