#!/usr/bin/env bash
set -ex

# format code
if [[ $CI ]]; then
    ./.venv/bin/black --check .
    ./.venv/bin/ruff .
else
    ./.venv/bin/black .
    ./.venv/bin/ruff . --fix
fi

# type check code
./.venv/bin/mypy .
